const sampleHomes = [{
  image: 'https://related-info-images.s3-us-west-2.amazonaws.com/andrea-davis-FHWCM78j66g-unsplash.jpg',
  reviews: 8,
  type: 'Private room',
  beds: 2,
  description: 'Cozy and quaint, but also haunted (by Elon Musk\'s time-travelling ghost)',
  price: 65,
  superhost: true,
  liked: false,
  city: 'Seattle, WA',
  url: 'https://www.google.com',
},
{
  image: 'https://related-info-images.s3-us-west-2.amazonaws.com/andrea-davis-FHWCM78j66g-unsplash.jpg',
  reviews: 0,
  type: 'Private room',
  beds: 2,
  description: 'Cozy and quaint, but also haunted (by Elon Musk\'s time-travelling ghost)',
  price: 65,
  superhost: false,
  liked: true,
  city: 'Seattle, WA',
  url: 'https://www.google.com',
},
{
  image: 'https://related-info-images.s3-us-west-2.amazonaws.com/andrea-davis-FHWCM78j66g-unsplash.jpg',
  reviews: 25,
  type: 'Private room',
  beds: 2,
  description: 'Cozy and quaint, but also haunted (by Elon Musk\'s time-travelling ghost)',
  price: 65,
  superhost: true,
  liked: true,
  city: 'Seattle, WA',
  url: 'https://www.google.com',
},
{
  image: 'https://related-info-images.s3-us-west-2.amazonaws.com/andrea-davis-FHWCM78j66g-unsplash.jpg',
  reviews: 0,
  type: 'Private room',
  beds: 2,
  description: 'Cozy and quaint, but also haunted (by Elon Musk\'s time-travelling ghost)',
  price: 65,
  superhost: false,
  liked: false,
  city: 'Seattle, WA',
  url: 'https://www.google.com',
},
{
  image: 'https://related-info-images.s3-us-west-2.amazonaws.com/andrea-davis-FHWCM78j66g-unsplash.jpg',
  reviews: 8,
  type: 'Private room',
  beds: 2,
  description: 'Cozy and quaint, but also haunted (by Elon Musk\'s time-travelling ghost)',
  price: 65,
  superhost: true,
  liked: false,
  city: 'Seattle, WA',
  url: 'https://www.google.com',
},
{
  image: 'https://related-info-images.s3-us-west-2.amazonaws.com/andrea-davis-FHWCM78j66g-unsplash.jpg',
  reviews: 0,
  type: 'Private room',
  beds: 2,
  description: 'Cozy and quaint, but also haunted (by Elon Musk\'s time-travelling ghost)',
  price: 65,
  superhost: false,
  liked: true,
  city: 'Seattle, WA',
  url: 'https://www.google.com',
},
{
  image: 'https://related-info-images.s3-us-west-2.amazonaws.com/andrea-davis-FHWCM78j66g-unsplash.jpg',
  reviews: 25,
  type: 'Private room',
  beds: 2,
  description: 'Cozy and quaint, but also haunted (by Elon Musk\'s time-travelling ghost)',
  price: 65,
  superhost: true,
  liked: true,
  city: 'Seattle, WA',
  url: 'https://www.google.com',
},
{
  image: 'https://related-info-images.s3-us-west-2.amazonaws.com/andrea-davis-FHWCM78j66g-unsplash.jpg',
  reviews: 0,
  type: 'Private room',
  beds: 2,
  description: 'Cozy and quaint, but also haunted (by Elon Musk\'s time-travelling ghost)',
  price: 65,
  superhost: false,
  liked: false,
  city: 'Seattle, WA',
  url: 'https://www.google.com',
},
{
  image: 'https://related-info-images.s3-us-west-2.amazonaws.com/andrea-davis-FHWCM78j66g-unsplash.jpg',
  reviews: 8,
  type: 'Private room',
  beds: 2,
  description: 'Cozy and quaint, but also haunted (by Elon Musk\'s time-travelling ghost)',
  price: 65,
  superhost: true,
  liked: false,
  city: 'Seattle, WA',
  url: 'https://www.google.com',
},
{
  image: 'https://related-info-images.s3-us-west-2.amazonaws.com/andrea-davis-FHWCM78j66g-unsplash.jpg',
  reviews: 0,
  type: 'Private room',
  beds: 2,
  description: 'Cozy and quaint, but also haunted (by Elon Musk\'s time-travelling ghost)',
  price: 65,
  superhost: false,
  liked: true,
  city: 'Seattle, WA',
  url: 'https://www.google.com',
},
{
  image: 'https://related-info-images.s3-us-west-2.amazonaws.com/andrea-davis-FHWCM78j66g-unsplash.jpg',
  reviews: 25,
  type: 'Private room',
  beds: 2,
  description: 'Cozy and quaint, but also haunted (by Elon Musk\'s time-travelling ghost)',
  price: 65,
  superhost: true,
  liked: true,
  city: 'Seattle, WA',
  url: 'https://www.google.com',
},
{
  image: 'https://related-info-images.s3-us-west-2.amazonaws.com/andrea-davis-FHWCM78j66g-unsplash.jpg',
  reviews: 0,
  type: 'Private room',
  beds: 2,
  description: 'Cozy and quaint, but also haunted (by Elon Musk\'s time-travelling ghost)',
  price: 65,
  superhost: false,
  liked: false,
  city: 'Seattle, WA',
  url: 'https://www.google.com',
},
{
  image: "https://unsplash.com/photos/ezRKQQPWJOw",
  reviews: 8,
  type: 'Entire house',
  beds: 4,
  description: 'It\'s definitely a house. Come check it out!',
  price: 235,
  superhost: false,
  liked: false,
  city: 'Oakland, CA',
  url: 'https://www.google.com',
},
{
  image: "https://unsplash.com/photos/ezRKQQPWJOw",
  reviews: 8,
  type: 'Entire house',
  beds: 4,
  description: 'It\'s definitely a house. Come check it out!',
  price: 235,
  superhost: false,
  liked: false,
  city: 'Oakland, CA',
  url: 'https://www.google.com',
},
{
  image: "https://unsplash.com/photos/ezRKQQPWJOw",
  reviews: 8,
  type: 'Entire house',
  beds: 4,
  description: 'It\'s definitely a house. Come check it out!',
  price: 235,
  superhost: false,
  liked: false,
  city: 'Oakland, CA',
  url: 'https://www.google.com',
},
{
  image: "https://unsplash.com/photos/ezRKQQPWJOw",
  reviews: 8,
  type: 'Entire house',
  beds: 4,
  description: 'It\'s definitely a house. Come check it out!',
  price: 235,
  superhost: false,
  liked: false,
  city: 'Oakland, CA',
  url: 'https://www.google.com',
},
{
  image: "https://unsplash.com/photos/ezRKQQPWJOw",
  reviews: 8,
  type: 'Entire house',
  beds: 4,
  description: 'It\'s definitely a house. Come check it out!',
  price: 235,
  superhost: false,
  liked: false,
  city: 'Oakland, CA',
  url: 'https://www.google.com',
},
{
  image: "https://unsplash.com/photos/ezRKQQPWJOw",
  reviews: 8,
  type: 'Entire house',
  beds: 4,
  description: 'It\'s definitely a house. Come check it out!',
  price: 235,
  superhost: false,
  liked: false,
  city: 'Oakland, CA',
  url: 'https://www.google.com',
},
{
  image: "https://unsplash.com/photos/ezRKQQPWJOw",
  reviews: 8,
  type: 'Entire house',
  beds: 4,
  description: 'It\'s definitely a house. Come check it out!',
  price: 235,
  superhost: false,
  liked: false,
  city: 'Oakland, CA',
  url: 'https://www.google.com',
},
{
  image: "https://unsplash.com/photos/ezRKQQPWJOw",
  reviews: 8,
  type: 'Entire house',
  beds: 4,
  description: 'It\'s definitely a house. Come check it out!',
  price: 235,
  superhost: false,
  liked: false,
  city: 'Oakland, CA',
  url: 'https://www.google.com',
},
{
  image: "https://unsplash.com/photos/ezRKQQPWJOw",
  reviews: 8,
  type: 'Entire house',
  beds: 4,
  description: 'It\'s definitely a house. Come check it out!',
  price: 235,
  superhost: false,
  liked: false,
  city: 'Oakland, CA',
  url: 'https://www.google.com',
},
{
  image: "https://unsplash.com/photos/ezRKQQPWJOw",
  reviews: 8,
  type: 'Entire house',
  beds: 4,
  description: 'It\'s definitely a house. Come check it out!',
  price: 235,
  superhost: false,
  liked: false,
  city: 'Oakland, CA',
  url: 'https://www.google.com',
},
{
  image: "https://unsplash.com/photos/ezRKQQPWJOw",
  reviews: 8,
  type: 'Entire house',
  beds: 4,
  description: 'It\'s definitely a house. Come check it out!',
  price: 235,
  superhost: false,
  liked: false,
  city: 'Oakland, CA',
  url: 'https://www.google.com',
},
{
  image: "https://unsplash.com/photos/ezRKQQPWJOw",
  reviews: 8,
  type: 'Entire house',
  beds: 4,
  description: 'It\'s definitely a house. Come check it out!',
  price: 235,
  superhost: false,
  liked: false,
  city: 'Oakland, CA',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/To7GxHUMq6g',
  reviews: 8,
  type: 'Shared room',
  beds: 1,
  description: 'The rats don\'t bite, as long as you\'re awake.',
  price: 115,
  superhost: false,
  liked: true,
  city: 'Hollywood, CA',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/To7GxHUMq6g',
  reviews: 8,
  type: 'Shared room',
  beds: 1,
  description: 'The rats don\'t bite, as long as you\'re awake.',
  price: 115,
  superhost: false,
  liked: true,
  city: 'Hollywood, CA',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/To7GxHUMq6g',
  reviews: 8,
  type: 'Shared room',
  beds: 1,
  description: 'The rats don\'t bite, as long as you\'re awake.',
  price: 115,
  superhost: false,
  liked: true,
  city: 'Hollywood, CA',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/To7GxHUMq6g',
  reviews: 8,
  type: 'Shared room',
  beds: 1,
  description: 'The rats don\'t bite, as long as you\'re awake.',
  price: 115,
  superhost: false,
  liked: true,
  city: 'Hollywood, CA',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/To7GxHUMq6g',
  reviews: 8,
  type: 'Shared room',
  beds: 1,
  description: 'The rats don\'t bite, as long as you\'re awake.',
  price: 115,
  superhost: false,
  liked: true,
  city: 'Hollywood, CA',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/To7GxHUMq6g',
  reviews: 8,
  type: 'Shared room',
  beds: 1,
  description: 'The rats don\'t bite, as long as you\'re awake.',
  price: 115,
  superhost: false,
  liked: true,
  city: 'Hollywood, CA',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/To7GxHUMq6g',
  reviews: 8,
  type: 'Shared room',
  beds: 1,
  description: 'The rats don\'t bite, as long as you\'re awake.',
  price: 115,
  superhost: false,
  liked: true,
  city: 'Hollywood, CA',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/To7GxHUMq6g',
  reviews: 8,
  type: 'Shared room',
  beds: 1,
  description: 'The rats don\'t bite, as long as you\'re awake.',
  price: 115,
  superhost: false,
  liked: true,
  city: 'Hollywood, CA',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/To7GxHUMq6g',
  reviews: 8,
  type: 'Shared room',
  beds: 1,
  description: 'The rats don\'t bite, as long as you\'re awake.',
  price: 115,
  superhost: false,
  liked: true,
  city: 'Hollywood, CA',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/To7GxHUMq6g',
  reviews: 8,
  type: 'Shared room',
  beds: 1,
  description: 'The rats don\'t bite, as long as you\'re awake.',
  price: 115,
  superhost: false,
  liked: true,
  city: 'Hollywood, CA',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/To7GxHUMq6g',
  reviews: 8,
  type: 'Shared room',
  beds: 1,
  description: 'The rats don\'t bite, as long as you\'re awake.',
  price: 115,
  superhost: false,
  liked: true,
  city: 'Hollywood, CA',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/To7GxHUMq6g',
  reviews: 8,
  type: 'Shared room',
  beds: 1,
  description: 'The rats don\'t bite, as long as you\'re awake.',
  price: 115,
  superhost: false,
  liked: true,
  city: 'Hollywood, CA',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/E9Udq-cPVXs',
  reviews: 0,
  type: 'Living room only',
  beds: 0,
  description: 'The best Des. Cap. experience you\'ll ever have',
  price: 18,
  superhost: false,
  liked: false,
  city: 'Austin, TX',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/E9Udq-cPVXs',
  reviews: 0,
  type: 'Living room only',
  beds: 0,
  description: 'The best Des. Cap. experience you\'ll ever have',
  price: 18,
  superhost: false,
  liked: false,
  city: 'Austin, TX',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/E9Udq-cPVXs',
  reviews: 0,
  type: 'Living room only',
  beds: 0,
  description: 'The best Des. Cap. experience you\'ll ever have',
  price: 18,
  superhost: false,
  liked: false,
  city: 'Austin, TX',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/E9Udq-cPVXs',
  reviews: 0,
  type: 'Living room only',
  beds: 0,
  description: 'The best Des. Cap. experience you\'ll ever have',
  price: 18,
  superhost: false,
  liked: false,
  city: 'Austin, TX',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/E9Udq-cPVXs',
  reviews: 0,
  type: 'Living room only',
  beds: 0,
  description: 'The best Des. Cap. experience you\'ll ever have',
  price: 18,
  superhost: false,
  liked: false,
  city: 'Austin, TX',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/E9Udq-cPVXs',
  reviews: 0,
  type: 'Living room only',
  beds: 0,
  description: 'The best Des. Cap. experience you\'ll ever have',
  price: 18,
  superhost: false,
  liked: false,
  city: 'Austin, TX',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/E9Udq-cPVXs',
  reviews: 0,
  type: 'Living room only',
  beds: 0,
  description: 'The best Des. Cap. experience you\'ll ever have',
  price: 18,
  superhost: false,
  liked: false,
  city: 'Austin, TX',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/E9Udq-cPVXs',
  reviews: 0,
  type: 'Living room only',
  beds: 0,
  description: 'The best Des. Cap. experience you\'ll ever have',
  price: 18,
  superhost: false,
  liked: false,
  city: 'Austin, TX',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/E9Udq-cPVXs',
  reviews: 0,
  type: 'Living room only',
  beds: 0,
  description: 'The best Des. Cap. experience you\'ll ever have',
  price: 18,
  superhost: false,
  liked: false,
  city: 'Austin, TX',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/E9Udq-cPVXs',
  reviews: 0,
  type: 'Living room only',
  beds: 0,
  description: 'The best Des. Cap. experience you\'ll ever have',
  price: 18,
  superhost: false,
  liked: false,
  city: 'Austin, TX',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/E9Udq-cPVXs',
  reviews: 0,
  type: 'Living room only',
  beds: 0,
  description: 'The best Des. Cap. experience you\'ll ever have',
  price: 18,
  superhost: false,
  liked: false,
  city: 'Austin, TX',
  url: 'https://www.google.com',
},
{
  image: 'https://unsplash.com/photos/E9Udq-cPVXs',
  reviews: 0,
  type: 'Living room only',
  beds: 0,
  description: 'The best Des. Cap. experience you\'ll ever have',
  price: 18,
  superhost: false,
  liked: false,
  city: 'Austin, TX',
  url: 'https://www.google.com',
}];

module.exports = sampleHomes;
