const sampleActivities = [{
  image: "https://unsplash.com/photos/16ziVZtz8vA",
  reviews: 12,
  description: 'An afternoon at the market: Come experience Pike\'s Place!',
  price: 45,
  liked: false,
  location: 'Pike Place Market, Seattle, WA',
  city: 'Seattle, WA',
},
{
  image: "https://unsplash.com/photos/16ziVZtz8vA",
  reviews: 12,
  description: 'An afternoon at the market: Come experience Pike\'s Place!',
  price: 45,
  liked: false,
  location: 'Pike Place Market, Seattle, WA',
  city: 'Seattle, WA',
},
{
  image: "https://unsplash.com/photos/16ziVZtz8vA",
  reviews: 12,
  description: 'An afternoon at the market: Come experience Pike\'s Place!',
  price: 45,
  liked: false,
  location: 'Pike Place Market, Seattle, WA',
  city: 'Seattle, WA',
},
{
  image: "https://unsplash.com/photos/16ziVZtz8vA",
  reviews: 12,
  description: 'An afternoon at the market: Come experience Pike\'s Place!',
  price: 45,
  liked: false,
  location: 'Pike Place Market, Seattle, WA',
  city: 'Seattle, WA',
},
{
  image: "https://unsplash.com/photos/16ziVZtz8vA",
  reviews: 12,
  description: 'An afternoon at the market: Come experience Pike\'s Place!',
  price: 45,
  liked: false,
  location: 'Pike Place Market, Seattle, WA',
  city: 'Seattle, WA',
},
{
  image: "https://unsplash.com/photos/16ziVZtz8vA",
  reviews: 12,
  description: 'An afternoon at the market: Come experience Pike\'s Place!',
  price: 45,
  liked: false,
  location: 'Pike Place Market, Seattle, WA',
  city: 'Seattle, WA',
},
{
  image: "https://unsplash.com/photos/16ziVZtz8vA",
  reviews: 12,
  description: 'An afternoon at the market: Come experience Pike\'s Place!',
  price: 45,
  liked: false,
  location: 'Pike Place Market, Seattle, WA',
  city: 'Seattle, WA',
},
{
  image: "https://unsplash.com/photos/16ziVZtz8vA",
  reviews: 12,
  description: 'An afternoon at the market: Come experience Pike\'s Place!',
  price: 45,
  liked: false,
  location: 'Pike Place Market, Seattle, WA',
  city: 'Seattle, WA',
},
{
  image: "https://unsplash.com/photos/16ziVZtz8vA",
  reviews: 12,
  description: 'An afternoon at the market: Come experience Pike\'s Place!',
  price: 45,
  liked: false,
  location: 'Pike Place Market, Seattle, WA',
  city: 'Seattle, WA',
},
{
  image: "https://unsplash.com/photos/16ziVZtz8vA",
  reviews: 12,
  description: 'An afternoon at the market: Come experience Pike\'s Place!',
  price: 45,
  liked: false,
  location: 'Pike Place Market, Seattle, WA',
  city: 'Seattle, WA',
},
{
  image: 'https://unsplash.com/photos/JDSjHhdgpZY',
  reviews: 1,
  description: 'Come check out this brown wooden dock. A favorite of Oakland locals!',
  price: 765,
  liked: false,
  location: 'Deep in the woods, by the water.',
  city: 'Oakland, CA',
},
{
  image: 'https://unsplash.com/photos/JDSjHhdgpZY',
  reviews: 1,
  description: 'Come check out this brown wooden dock. A favorite of Oakland locals!',
  price: 765,
  liked: false,
  location: 'Deep in the woods, by the water.',
  city: 'Oakland, CA',
},
{
  image: 'https://unsplash.com/photos/JDSjHhdgpZY',
  reviews: 1,
  description: 'Come check out this brown wooden dock. A favorite of Oakland locals!',
  price: 765,
  liked: false,
  location: 'Deep in the woods, by the water.',
  city: 'Oakland, CA',
},
{
  image: 'https://unsplash.com/photos/JDSjHhdgpZY',
  reviews: 1,
  description: 'Come check out this brown wooden dock. A favorite of Oakland locals!',
  price: 765,
  liked: false,
  location: 'Deep in the woods, by the water.',
  city: 'Oakland, CA',
},
{
  image: 'https://unsplash.com/photos/JDSjHhdgpZY',
  reviews: 1,
  description: 'Come check out this brown wooden dock. A favorite of Oakland locals!',
  price: 765,
  liked: false,
  location: 'Deep in the woods, by the water.',
  city: 'Oakland, CA',
},
{
  image: 'https://unsplash.com/photos/JDSjHhdgpZY',
  reviews: 1,
  description: 'Come check out this brown wooden dock. A favorite of Oakland locals!',
  price: 765,
  liked: false,
  location: 'Deep in the woods, by the water.',
  city: 'Oakland, CA',
},
{
  image: 'https://unsplash.com/photos/JDSjHhdgpZY',
  reviews: 1,
  description: 'Come check out this brown wooden dock. A favorite of Oakland locals!',
  price: 765,
  liked: false,
  location: 'Deep in the woods, by the water.',
  city: 'Oakland, CA',
},
{
  image: 'https://unsplash.com/photos/JDSjHhdgpZY',
  reviews: 1,
  description: 'Come check out this brown wooden dock. A favorite of Oakland locals!',
  price: 765,
  liked: false,
  location: 'Deep in the woods, by the water.',
  city: 'Oakland, CA',
},
{
  image: 'https://unsplash.com/photos/JDSjHhdgpZY',
  reviews: 1,
  description: 'Come check out this brown wooden dock. A favorite of Oakland locals!',
  price: 765,
  liked: false,
  location: 'Deep in the woods, by the water.',
  city: 'Oakland, CA',
},
{
  image: 'https://unsplash.com/photos/JDSjHhdgpZY',
  reviews: 1,
  description: 'Come check out this brown wooden dock. A favorite of Oakland locals!',
  price: 765,
  liked: false,
  location: 'Deep in the woods, by the water.',
  city: 'Oakland, CA',
},
{
  image: 'https://unsplash.com/photos/8LlJNFLTEm0',
  reviews: 25,
  description: 'Celebrities nowhere. Tourists everywhere. You\'re gonna love this tour!',
  price: 125,
  liked: true,
  city: 'Hollywood, CA',
},
{
  image: 'https://unsplash.com/photos/8LlJNFLTEm0',
  reviews: 25,
  description: 'Celebrities nowhere. Tourists everywhere. You\'re gonna love this tour!',
  price: 125,
  liked: true,
  city: 'Hollywood, CA',
},
{
  image: 'https://unsplash.com/photos/8LlJNFLTEm0',
  reviews: 25,
  description: 'Celebrities nowhere. Tourists everywhere. You\'re gonna love this tour!',
  price: 125,
  liked: true,
  city: 'Hollywood, CA',
},
{
  image: 'https://unsplash.com/photos/8LlJNFLTEm0',
  reviews: 25,
  description: 'Celebrities nowhere. Tourists everywhere. You\'re gonna love this tour!',
  price: 125,
  liked: true,
  city: 'Hollywood, CA',
},
{
  image: 'https://unsplash.com/photos/8LlJNFLTEm0',
  reviews: 25,
  description: 'Celebrities nowhere. Tourists everywhere. You\'re gonna love this tour!',
  price: 125,
  liked: true,
  city: 'Hollywood, CA',
},
{
  image: 'https://unsplash.com/photos/8LlJNFLTEm0',
  reviews: 25,
  description: 'Celebrities nowhere. Tourists everywhere. You\'re gonna love this tour!',
  price: 125,
  liked: true,
  city: 'Hollywood, CA',
},
{
  image: 'https://unsplash.com/photos/8LlJNFLTEm0',
  reviews: 25,
  description: 'Celebrities nowhere. Tourists everywhere. You\'re gonna love this tour!',
  price: 125,
  liked: true,
  city: 'Hollywood, CA',
},
{
  image: 'https://unsplash.com/photos/8LlJNFLTEm0',
  reviews: 25,
  description: 'Celebrities nowhere. Tourists everywhere. You\'re gonna love this tour!',
  price: 125,
  liked: true,
  city: 'Hollywood, CA',
},
{
  image: 'https://unsplash.com/photos/8LlJNFLTEm0',
  reviews: 25,
  description: 'Celebrities nowhere. Tourists everywhere. You\'re gonna love this tour!',
  price: 125,
  liked: true,
  city: 'Hollywood, CA',
},
{
  image: 'https://unsplash.com/photos/8LlJNFLTEm0',
  reviews: 25,
  description: 'Celebrities nowhere. Tourists everywhere. You\'re gonna love this tour!',
  price: 125,
  liked: true,
  city: 'Hollywood, CA',
},
{
  image: 'https://unsplash.com/photos/HFbzqwfnrsE',
  reviews: 68,
  description: 'Paddleboarding lessons! Just don\'t fall in!',
  price: 70,
  liked: true,
  location: 'Butler Shores at Town Lake Metro Park Trail, Austin, TX',
  city: 'Austin, TX',
},
{
  image: 'https://unsplash.com/photos/HFbzqwfnrsE',
  reviews: 68,
  description: 'Paddleboarding lessons! Just don\'t fall in!',
  price: 70,
  liked: true,
  location: 'Butler Shores at Town Lake Metro Park Trail, Austin, TX',
  city: 'Austin, TX',
},
{
  image: 'https://unsplash.com/photos/HFbzqwfnrsE',
  reviews: 68,
  description: 'Paddleboarding lessons! Just don\'t fall in!',
  price: 70,
  liked: true,
  location: 'Butler Shores at Town Lake Metro Park Trail, Austin, TX',
  city: 'Austin, TX',
},
{
  image: 'https://unsplash.com/photos/HFbzqwfnrsE',
  reviews: 68,
  description: 'Paddleboarding lessons! Just don\'t fall in!',
  price: 70,
  liked: true,
  location: 'Butler Shores at Town Lake Metro Park Trail, Austin, TX',
  city: 'Austin, TX',
},
{
  image: 'https://unsplash.com/photos/HFbzqwfnrsE',
  reviews: 68,
  description: 'Paddleboarding lessons! Just don\'t fall in!',
  price: 70,
  liked: true,
  location: 'Butler Shores at Town Lake Metro Park Trail, Austin, TX',
  city: 'Austin, TX',
},
{
  image: 'https://unsplash.com/photos/HFbzqwfnrsE',
  reviews: 68,
  description: 'Paddleboarding lessons! Just don\'t fall in!',
  price: 70,
  liked: true,
  location: 'Butler Shores at Town Lake Metro Park Trail, Austin, TX',
  city: 'Austin, TX',
},
{
  image: 'https://unsplash.com/photos/HFbzqwfnrsE',
  reviews: 68,
  description: 'Paddleboarding lessons! Just don\'t fall in!',
  price: 70,
  liked: true,
  location: 'Butler Shores at Town Lake Metro Park Trail, Austin, TX',
  city: 'Austin, TX',
},
{
  image: 'https://unsplash.com/photos/HFbzqwfnrsE',
  reviews: 68,
  description: 'Paddleboarding lessons! Just don\'t fall in!',
  price: 70,
  liked: true,
  location: 'Butler Shores at Town Lake Metro Park Trail, Austin, TX',
  city: 'Austin, TX',
},
{
  image: 'https://unsplash.com/photos/HFbzqwfnrsE',
  reviews: 68,
  description: 'Paddleboarding lessons! Just don\'t fall in!',
  price: 70,
  liked: true,
  location: 'Butler Shores at Town Lake Metro Park Trail, Austin, TX',
  city: 'Austin, TX',
},
{
  image: 'https://unsplash.com/photos/HFbzqwfnrsE',
  reviews: 68,
  description: 'Paddleboarding lessons! Just don\'t fall in!',
  price: 70,
  liked: true,
  location: 'Butler Shores at Town Lake Metro Park Trail, Austin, TX',
  city: 'Austin, TX',
}];

module.exports = sampleActivities;
